# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Hotel Booking 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Teste-Ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: python -m unittest discover -v
  
  Teste-Windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: python -m unittest discover -v
  
  Teste-Mac:
    name: Test on Mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: python -m unittest discover -v